name: Build

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - .gitignore
      - "docs/**"
      - ".github/**"
      - README.md

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  wip:
    name: wip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
